services:
  - docker

before_install:
  - docker build -t hankewyczz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hankewyczz/react-test npm test

after_success:
  - docker build -t hankewyczz/multi-client ./client
  - docker build -t hankewyczz/multi-nginx ./nginx
  - docker build -t hankewyczz/multi-server ./server
  - docker build -t hankewyczz/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker hub
  - docker push hankewyczz/multi-client
  - docker push hankewyczz/multi-nginx
  - docker push hankewyczz/multi-server
  - docker push hankewyczz/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: Multidocker-env
  bucket: elasticbeanstalk-us-east-2-577111805146
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY